import type { Config } from "tailwindcss"
import tailwindcssAnimate from "tailwindcss-animate"

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/app/**/*.{ts,tsx}",
    "./src/components/**/*.{ts,tsx}",
    "./src/hooks/**/*.{ts,tsx}",
    "./src/lib/**/*.{ts,tsx}",
    "./src/services/**/*.{ts,tsx}",
    "./src/ui/**/*.{ts,tsx}",
    "./src/tailwind-cms-content.html", // ← auto-generated by scripts/extract-cms-classes.js
  ],
  safelist: [
    // Only literal classes that Tailwind's scanner might miss
    // (e.g. built conditionally in JS: `isActive ? "bg-blue-500" : "bg-gray-200"`)
    "container", "group", "peer", "sr-only", "not-sr-only",
    "list-none", "list-disc", "list-decimal",
    "underline", "line-through", "no-underline",
    "uppercase", "lowercase", "capitalize", "normal-case",
    "italic", "not-italic",
    "truncate", "overflow-hidden", "overflow-visible", "overflow-scroll",
    "overflow-x-auto", "overflow-y-auto", "overflow-x-hidden", "overflow-y-hidden",
    "object-cover", "object-contain", "object-fill", "object-center",
    "pointer-events-none", "pointer-events-auto",
    "select-none", "select-text", "select-all",
    "cursor-pointer", "cursor-default", "cursor-not-allowed",
    // Add any other literal classes YOUR OWN components conditionally toggle in JS
    // (not CMS-typed — those are covered by the scan file now)
  ],
  theme: {
    extend: {
      colors: {
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
        sidebar: {
          DEFAULT: "var(--sidebar)",
          foreground: "var(--sidebar-foreground)",
          primary: "var(--sidebar-primary)",
          "primary-foreground": "var(--sidebar-primary-foreground)",
          accent: "var(--sidebar-accent)",
          "accent-foreground": "var(--sidebar-accent-foreground)",
          border: "var(--sidebar-border)",
          ring: "var(--sidebar-ring)",
        },
        success: "var(--success)",
        chart: {
          "1": "var(--chart-1)",
          "2": "var(--chart-2)",
          "3": "var(--chart-3)",
          "4": "var(--chart-4)",
          "5": "var(--chart-5)",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      height: {
        125: "31.25rem",
      },
    },
  },
  plugins: [tailwindcssAnimate],
}

export default config