export async function GET() {
  const sitemapXsl = `<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns="http://www.w3.org/1999/xhtml">
  <xsl:output method="html" encoding="UTF-8" indent="yes"/>

  <xsl:template match="/">
    <html lang="en">
      <head>
        <title>XML Sitemap</title>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <style>
        <![CDATA[
          body {
            margin: 0;
            background: #f6f7f9;
            color: #1d2327;
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
            font-size: 14px;
          }
          .wrap {
            max-width: 1100px;
            margin: 0 auto;
            padding: 36px 24px;
          }
          h1 {
            margin: 0 0 8px;
            font-size: 28px;
            font-weight: 600;
          }
          p {
            margin: 0 0 24px;
            color: #646970;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            background: #fff;
            border: 1px solid #c3c4c7;
            box-shadow: 0 1px 1px rgba(0, 0, 0, 0.04);
          }
          th {
            background: #f0f0f1;
            border-bottom: 1px solid #c3c4c7;
            color: #1d2327;
            font-weight: 600;
            text-align: left;
          }
          th, td {
            padding: 12px 14px;
            border-bottom: 1px solid #dcdcde;
            vertical-align: top;
          }
          tr:nth-child(even) td {
            background: #fbfbfc;
          }
          a {
            color: #2271b1;
            text-decoration: none;
            word-break: break-all;
          }
          a:hover {
            color: #135e96;
            text-decoration: underline;
          }
          .count {
            display: inline-block;
            margin: 8px 0 18px;
            color: #646970;
            font-size: 12px;
          }
          @media (max-width: 768px) {
            .wrap {
              padding: 24px 16px;
            }
            h1 {
              font-size: 20px;
            }
            table {
              font-size: 12px;
            }
            th, td {
              padding: 8px 10px;
            }
          }
        ]]>
        </style>
      </head>
      <body>
        <div class="wrap">
          <h1>XML Sitemap</h1>
          <p>This XML sitemap is generated by the site and helps search engines discover public URLs.</p>
          <span class="count">
            Total entries: <xsl:value-of select="count(sitemap:urlset/sitemap:url) + count(sitemap:sitemapindex/sitemap:sitemap)"/>
          </span>

          <xsl:choose>
            <xsl:when test="sitemap:sitemapindex">
              <table>
                <thead>
                  <tr>
                    <th>Sitemap</th>
                    <th>Last Modified</th>
                  </tr>
                </thead>
                <tbody>
                  <xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
                    <tr>
                      <td>
                        <a>
                          <xsl:attribute name="href">
                            <xsl:value-of select="sitemap:loc"/>
                          </xsl:attribute>
                          <xsl:value-of select="sitemap:loc"/>
                        </a>
                      </td>
                      <td>
                        <xsl:choose>
                          <xsl:when test="sitemap:lastmod">
                            <xsl:value-of select="sitemap:lastmod"/>
                          </xsl:when>
                          <xsl:otherwise>-</xsl:otherwise>
                        </xsl:choose>
                      </td>
                    </tr>
                  </xsl:for-each>
                </tbody>
              </table>
            </xsl:when>
            <xsl:otherwise>
              <table>
                <thead>
                  <tr>
                    <th>URL</th>
                    <th>Last Modified</th>
                    <th>Change Frequency</th>
                    <th>Priority</th>
                  </tr>
                </thead>
                <tbody>
                  <xsl:for-each select="sitemap:urlset/sitemap:url">
                    <tr>
                      <td>
                        <a>
                          <xsl:attribute name="href">
                            <xsl:value-of select="sitemap:loc"/>
                          </xsl:attribute>
                          <xsl:value-of select="sitemap:loc"/>
                        </a>
                      </td>
                      <td>
                        <xsl:choose>
                          <xsl:when test="sitemap:lastmod">
                            <xsl:value-of select="sitemap:lastmod"/>
                          </xsl:when>
                          <xsl:otherwise>-</xsl:otherwise>
                        </xsl:choose>
                      </td>
                      <td>
                        <xsl:choose>
                          <xsl:when test="sitemap:changefreq">
                            <xsl:value-of select="sitemap:changefreq"/>
                          </xsl:when>
                          <xsl:otherwise>-</xsl:otherwise>
                        </xsl:choose>
                      </td>
                      <td>
                        <xsl:choose>
                          <xsl:when test="sitemap:priority">
                            <xsl:value-of select="sitemap:priority"/>
                          </xsl:when>
                          <xsl:otherwise>-</xsl:otherwise>
                        </xsl:choose>
                      </td>
                    </tr>
                  </xsl:for-each>
                </tbody>
              </table>
            </xsl:otherwise>
          </xsl:choose>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>`;

  return new Response(sitemapXsl, {
    headers: {
      "Content-Type": "application/xslt+xml; charset=utf-8",
      "Cache-Control": "public, max-age=604800",
    },
  });
}
