import { prisma } from "../../prisma.js";
import { requirePermission } from "../../withPermission.js";

const defaults = { enabled: false, consentVersion: "1", bannerTitle: "We use cookies", bannerDescription: "We use cookies to improve your experience and understand how our site is used.", position: "bottom", acceptAllText: "Accept All", rejectAllText: "Reject All", customizeText: "Customize", privacyPolicyUrl: null };
const defaultCategories = [{ name: "Necessary", slug: "necessary", description: "Required for the website to function.", required: true }, { name: "Preferences", slug: "preferences", description: "Remember your choices and settings.", required: false }, { name: "Analytics", slug: "analytics", description: "Help us understand how visitors use the site.", required: false }, { name: "Marketing", slug: "marketing", description: "Support relevant advertising and campaigns.", required: false }];

async function tenantId() { const { session } = await requirePermission("settings_manage"); return Number(session.user.tenantId); }
export async function getCookieConsentAdmin() { const id = await tenantId(); let settings = await prisma.cookieConsentSettings.findUnique({ where: { tenantId: id } }); if (!settings) settings = await prisma.cookieConsentSettings.create({ data: { ...defaults, tenant: { connect: { id } } } }); let categories = await prisma.cookieCategory.findMany({ where: { tenantId: id }, include: { cookies: true }, orderBy: { sortOrder: "asc" } }); if (!categories.length) { await prisma.cookieCategory.createMany({ data: defaultCategories.map((c, i) => ({ ...c, tenantId: id, sortOrder: i })) }); categories = await prisma.cookieCategory.findMany({ where: { tenantId: id }, include: { cookies: true }, orderBy: { sortOrder: "asc" } }); } return { settings, categories }; }
export async function updateCookieSettings(input) { const id = await tenantId(); return prisma.cookieConsentSettings.upsert({ where: { tenantId: id }, create: { ...defaults, ...input, tenantId: id }, update: { ...input } }); }
export async function listCategories() { const id = await tenantId(); return prisma.cookieCategory.findMany({ where: { tenantId: id }, include: { cookies: true }, orderBy: { sortOrder: "asc" } }); }
export async function saveCategory(input, categoryId) { const id = await tenantId(); const data = { name: String(input.name || "").trim(), slug: String(input.slug || input.name || "").trim().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""), description: input.description || null, required: Boolean(input.required), enabled: input.enabled !== false, sortOrder: Number(input.sortOrder || 0) }; if (!data.name || !data.slug) throw new Error("Category name is required"); return categoryId ? prisma.cookieCategory.update({ where: { id: categoryId, tenantId: id }, data }) : prisma.cookieCategory.create({ data: { ...data, tenantId: id } }); }
export async function deleteCategory(categoryId) { const id = await tenantId(); return prisma.cookieCategory.delete({ where: { id: categoryId, tenantId: id } }); }
export async function saveCookie(input, cookieId) { const id = await tenantId(); const category = await prisma.cookieCategory.findFirst({ where: { id: input.categoryId, tenantId: id } }); if (!category) throw new Error("Invalid cookie category"); const data = { categoryId: input.categoryId, name: String(input.name || "").trim(), provider: input.provider || null, description: input.description || null, duration: input.duration || null, pattern: input.pattern || null }; if (!data.name) throw new Error("Cookie name is required"); return cookieId ? prisma.cookieDefinition.update({ where: { id: cookieId, tenantId: id }, data }) : prisma.cookieDefinition.create({ data: { ...data, tenantId: id } }); }
export async function deleteCookie(cookieId) { const id = await tenantId(); return prisma.cookieDefinition.delete({ where: { id: cookieId, tenantId: id } }); }
export async function getPublicCookieConfig() { const settings = await prisma.cookieConsentSettings.findFirst().catch(() => null); if (!settings) return { enabled: false, consentVersion: "1", banner: defaults, categories: [], privacyPolicyUrl: null }; const categories = await prisma.cookieCategory.findMany({ where: { tenantId: settings.tenantId, enabled: true }, select: { name: true, slug: true, description: true, required: true, sortOrder: true }, orderBy: { sortOrder: "asc" } }); return { enabled: settings.enabled, consentVersion: settings.consentVersion, banner: { title: settings.bannerTitle, description: settings.bannerDescription, position: settings.position, acceptAllText: settings.acceptAllText, rejectAllText: settings.rejectAllText, customizeText: settings.customizeText }, categories, privacyPolicyUrl: settings.privacyPolicyUrl }; }
