// import { Plugin, PluginStats } from '@/types/plugins';

import { PluginStats, Plugin } from "@/src/types/plugins";

export const availablePlugins: Plugin[] = [
  {
    id: 'forms',
    name: 'Forms',
    description: 'Create beautiful forms and manage submissions easily.',
    version: 'v1.0.0',
    icon: '📝',
    category: 'content',
    status: 'installed',
    installed: true,
    lastUpdated: '2 days ago',
  },
  {
    id: 'ecommerce',
    name: 'Ecommerce',
    description: 'Manage products, orders, customers and more.',
    version: 'v1.0.0',
    icon: '🛍️',
    category: 'ecommerce',
    status: 'available',
    installed: false,
  },
  {
    id: 'seo',
    name: 'SEO',
    description: 'Improve SEO, manage meta, sitemaps and redirects.',
    version: 'v1.0.0',
    icon: '🔍',
    category: 'marketing',
    status: 'available',
    installed: false,
  },
  {
    id: 'subscription-billing',
    name: 'Subscription & Billing',
    description: 'Add subscription plans, payments and recurring billing.',
    version: 'v1.0.0',
    icon: '💰',
    category: 'ecommerce',
    status: 'available',
    installed: false,
  },
  {
    id: 'analytics-ai',
    name: 'Analytics & AI',
    description: 'Track analytics and get AI-powered insights.',
    version: 'v1.0.0',
    icon: '🤖',
    category: 'integrations',
    status: 'available',
    installed: false,
  },
  {
    id: 'comments',
    name: 'Comments',
    description: 'Advanced comments system with moderation.',
    version: 'v1.0.0',
    icon: '💬',
    category: 'content',
    status: 'available',
    installed: false,
  },
  {
    id: 'file-sharing',
    name: 'File Sharing',
    description: 'Allow users to upload, share and manage files.',
    version: 'v1.0.0',
    icon: '📁',
    category: 'utilities',
    status: 'available',
    installed: false,
  },
  {
    id: 'emails',
    name: 'Emails',
    description: 'Email templates, SMTP settings and email logs.',
    version: 'v1.0.0',
    icon: '✉️',
    category: 'utilities',
    status: 'available',
    installed: false,
  },
  {
    id: 'social-login',
    name: 'Social Login',
    description: 'Enable login with social providers.',
    version: 'v1.0.0',
    icon: '🔐',
    category: 'users',
    status: 'available',
    installed: false,
  },
  {
    id: 'backup-restore',
    name: 'Backup & Restore',
    description: 'Automated backup and one-click restore.',
    version: 'v1.0.0',
    icon: '💾',
    category: 'utilities',
    status: 'available',
    installed: false,
  },
  {
    id: 'multi-language',
    name: 'Multi Language',
    description: 'Add multilingual support.',
    version: 'v1.0.0',
    icon: '🌐',
    category: 'utilities',
    status: 'available',
    installed: false,
  },
  {
    id: 'maintenance-mode',
    name: 'Maintenance Mode',
    description: 'Put your site into maintenance mode.',
    version: 'v1.0.0',
    icon: '🛠️',
    category: 'utilities',
    status: 'available',
    installed: false,
  },
];

export const installedPlugins: Plugin[] = [
  {
    id: 'forms',
    name: 'Forms',
    description: 'Create beautiful forms and manage submissions easily.',
    version: 'v1.0.0',
    icon: '📝',
    category: 'content',
    status: 'active',
    installed: true,
    lastUpdated: '2 days ago',
    actions: {
      settings: true,
      deactivate: true,
      viewDetails: true,
      checkUpdates: true,
    },
  },
  {
    id: 'ecommerce',
    name: 'Ecommerce',
    description: 'Manage products, orders, customers and more.',
    version: 'v1.0.0',
    icon: '🛍️',
    category: 'ecommerce',
    status: 'active',
    installed: true,
    lastUpdated: '1 day ago',
    actions: {
      settings: true,
      deactivate: true,
      viewDetails: true,
      checkUpdates: true,
    },
  },
  {
    id: 'seo',
    name: 'SEO',
    description: 'Improve SEO, manage meta, sitemaps and redirects.',
    version: 'v1.0.0',
    icon: '🔍',
    category: 'marketing',
    status: 'active',
    installed: true,
    lastUpdated: '3 days ago',
    actions: {
      settings: true,
      deactivate: true,
      viewDetails: true,
      checkUpdates: true,
    },
  },
  {
    id: 'subscription-billing',
    name: 'Subscription & Billing',
    description: 'Add subscription plans, payments and recurring billing.',
    version: 'v1.0.0',
    icon: '💰',
    category: 'ecommerce',
    status: 'active',
    installed: true,
    lastUpdated: '5 days ago',
    actions: {
      settings: true,
      deactivate: true,
      viewDetails: true,
      checkUpdates: true,
    },
  },
  {
    id: 'analytics-ai',
    name: 'Analytics & AI',
    description: 'Track analytics and get AI-powered insights.',
    version: 'v1.0.0',
    icon: '🤖',
    category: 'integrations',
    status: 'active',
    installed: true,
    lastUpdated: '6 hours ago',
    actions: {
      settings: true,
      deactivate: true,
      viewDetails: true,
      checkUpdates: true,
    },
  },
  {
    id: 'comments',
    name: 'Comments',
    description: 'Advanced comments system with moderation.',
    version: 'v1.0.0',
    icon: '💬',
    category: 'content',
    status: 'inactive',
    installed: true,
    lastUpdated: '1 week ago',
    actions: {
      activate: true,
      settings: true,
      viewDetails: true,
      uninstall: true,
    },
  },
  {
    id: 'file-sharing',
    name: 'File Sharing',
    description: 'Allow users to upload, share and manage files.',
    version: 'v1.0.0',
    icon: '📁',
    category: 'utilities',
    status: 'inactive',
    installed: true,
    lastUpdated: '1 week ago',
    actions: {
      activate: true,
      settings: true,
      viewDetails: true,
      uninstall: true,
    },
  },
  {
    id: 'emails',
    name: 'Emails',
    description: 'Email templates, SMTP settings and email logs.',
    version: 'v1.0.0',
    icon: '✉️',
    category: 'utilities',
    status: 'inactive',
    installed: true,
    lastUpdated: '2 weeks ago',
    actions: {
      activate: true,
      settings: true,
      viewDetails: true,
      uninstall: true,
    },
  },
  {
    id: 'backup-restore',
    name: 'Backup & Restore',
    description: 'Automated backup and one-click restore.',
    version: 'v1.0.0',
    icon: '💾',
    category: 'utilities',
    status: 'inactive',
    installed: true,
    lastUpdated: '2 weeks ago',
    actions: {
      activate: true,
      settings: true,
      viewDetails: true,
      uninstall: true,
    },
  },
  {
    id: 'multi-language',
    name: 'Multi Language',
    description: 'Add multilingual support.',
    version: 'v1.0.0',
    icon: '🌐',
    category: 'utilities',
    status: 'inactive',
    installed: true,
    lastUpdated: '3 weeks ago',
    actions: {
      activate: true,
      settings: true,
      viewDetails: true,
      uninstall: true,
    },
  },
];

export const pluginStats: PluginStats = {
  total: 10,
  active: 6,
  inactive: 4,
  updatesAvailable: 2,
};

export const categories = [
  { id: 'all', label: 'All' },
  { id: 'content', label: 'Content' },
  { id: 'marketing', label: 'Marketing' },
  { id: 'ecommerce', label: 'Ecommerce' },
  { id: 'users', label: 'Users' },
  { id: 'utilities', label: 'Utilities' },
  { id: 'integrations', label: 'Integrations' },
];

export const getCategoryIcon = (category: string): string => {
  const icons: Record<string, string> = {
    content: '📄',
    marketing: '📊',
    ecommerce: '🛒',
    users: '👤',
    utilities: '🔧',
    integrations: '🔗',
  };
  return icons[category] || '📦';
};